# Generated by Django 2.0.6 on 2018-06-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='hrefFamily',
            field=models.CharField(default='font-family', max_length=100),
        ),
    ]
